/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartProductItemRequest } from './cartProductItemRequest';

export class AddProductItemsRequest {
    /**
    * A list of Product items to be added to the shopping cart.
    */
    'productItems': Array<CartProductItemRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productItems",
            "baseName": "productItems",
            "type": "Array<CartProductItemRequest>"
        }    ];

    static getAttributeTypeMap() {
        return AddProductItemsRequest.attributeTypeMap;
    }
}

