/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProductItemRequest } from './productItemRequest';

export class BaseCategory {
    /**
    * The name of the product category.
    */
    'name': string;
    /**
    * The display order of the product category.
    */
    'displayOrder'?: number;
    /**
    * Products to be created within the category.
    */
    'items'?: Array<ProductItemRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "displayOrder",
            "baseName": "displayOrder",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ProductItemRequest>"
        }    ];

    static getAttributeTypeMap() {
        return BaseCategory.attributeTypeMap;
    }
}

