/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CartSubscriptionItem {
    /**
    * Unit ID
    */
    'unitId'?: string;
    /**
    * Subscription Product ID
    */
    'subscriptionProductId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "subscriptionProductId",
            "baseName": "subscriptionProductId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CartSubscriptionItem.attributeTypeMap;
    }
}

