/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CartStatusResponse {
    /**
    * Status ID
    */
    'cartStatusId': number;
    /**
    * Display name
    */
    'displayName': string;
    /**
    * Code name
    */
    'codeName': string;
    /**
    * Status description
    */
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cartStatusId",
            "baseName": "cartStatusId",
            "type": "number"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "codeName",
            "baseName": "codeName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CartStatusResponse.attributeTypeMap;
    }
}

