/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CartProductItemResponse {
    /**
    * Id
    */
    'cartProductItemId': string;
    /**
    * Product Site ID
    */
    'productSiteId': string;
    /**
    * Product ID
    */
    'productId': string;
    /**
    * Site ID
    */
    'siteId': string;
    /**
    * Quantity
    */
    'quantity': number;
    /**
    * The price of the product in the smallest currency unit (e.g. cents for USD).
    */
    'price': number;
    /**
    * The identifier for this product site record in the current payment provider.
    */
    'paymentProviderId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cartProductItemId",
            "baseName": "cartProductItemId",
            "type": "string"
        },
        {
            "name": "productSiteId",
            "baseName": "productSiteId",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "paymentProviderId",
            "baseName": "paymentProviderId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CartProductItemResponse.attributeTypeMap;
    }
}

