/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CartItemTaxResponse {
    /**
    * Cart Item Tax ID
    */
    'cartItemTaxId': string;
    /**
    * Cart Item ID
    */
    'cartItemId': string;
    /**
    * Tax Rate ID
    */
    'taxRateId': string;
    /**
    * amount
    */
    'amount': number;
    /**
    * amount
    */
    'rate': number;
    /**
    * Tax description
    */
    'description': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cartItemTaxId",
            "baseName": "cartItemTaxId",
            "type": "string"
        },
        {
            "name": "cartItemId",
            "baseName": "cartItemId",
            "type": "string"
        },
        {
            "name": "taxRateId",
            "baseName": "taxRateId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CartItemTaxResponse.attributeTypeMap;
    }
}

