/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CartSubscriptionItemUnitResponse {
    /**
    * Unit ID
    */
    'unitId': string;
    /**
    * User-friendly display name for the unit; i.e unit name/label.
    */
    'unitName': string;
    /**
    * Standard monthly price
    */
    'standardPrice': number;
    /**
    * Pro-rated price
    */
    'price': number;
    /**
    * Total days in the month (used for pro-rated price)
    */
    'totalDaysInMonth': number;
    /**
    * Remaining days in the month (used for pro-rated price)
    */
    'remainingDaysInMonth': number;
    /**
    * Status ID
    */
    'statusId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string"
        },
        {
            "name": "standardPrice",
            "baseName": "standardPrice",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "totalDaysInMonth",
            "baseName": "totalDaysInMonth",
            "type": "number"
        },
        {
            "name": "remainingDaysInMonth",
            "baseName": "remainingDaysInMonth",
            "type": "number"
        },
        {
            "name": "statusId",
            "baseName": "statusId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CartSubscriptionItemUnitResponse.attributeTypeMap;
    }
}

