/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartFeeResponse } from './cartFeeResponse';
import { CartItemResponse } from './cartItemResponse';
import { CartItemStatus } from './cartItemStatus';
import { CartStatus } from './cartStatus';
import { CartSubscriptionItemResponse } from './cartSubscriptionItemResponse';
import { CartTaxResponse } from './cartTaxResponse';

export class CartV2Response {
    /**
    * Cart ID
    */
    'cartId': string;
    /**
    * Org ID
    */
    'orgId': string;
    /**
    * Site ID
    */
    'siteId': string;
    /**
    * User ID
    */
    'userId': string;
    /**
    * Account ID
    */
    'accountId': string;
    'cartStatus': CartStatus;
    'notes': string | null;
    'comments': string | null;
    'cartSubscriptionItems': Array<CartSubscriptionItemResponse>;
    'cartItems': Array<CartItemResponse>;
    'cartFees': Array<CartFeeResponse>;
    'cartItemsStatus': CartItemStatus;
    'cartTotal': number;
    'cartTaxes': Array<CartTaxResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cartId",
            "baseName": "cartId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "cartStatus",
            "baseName": "cartStatus",
            "type": "CartStatus"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string"
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "string"
        },
        {
            "name": "cartSubscriptionItems",
            "baseName": "cartSubscriptionItems",
            "type": "Array<CartSubscriptionItemResponse>"
        },
        {
            "name": "cartItems",
            "baseName": "cartItems",
            "type": "Array<CartItemResponse>"
        },
        {
            "name": "cartFees",
            "baseName": "cartFees",
            "type": "Array<CartFeeResponse>"
        },
        {
            "name": "cartItemsStatus",
            "baseName": "cartItemsStatus",
            "type": "CartItemStatus"
        },
        {
            "name": "cartTotal",
            "baseName": "cartTotal",
            "type": "number"
        },
        {
            "name": "cartTaxes",
            "baseName": "cartTaxes",
            "type": "Array<CartTaxResponse>"
        }    ];

    static getAttributeTypeMap() {
        return CartV2Response.attributeTypeMap;
    }
}

export namespace CartV2Response {
}
