/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartSubscriptionItem } from './cartSubscriptionItem';

export class CreateCartSubscriptionItemsRequest {
    /**
    * A list of subscription items to be added to the cart.
    */
    'cartSubscriptionItems': Array<CartSubscriptionItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cartSubscriptionItems",
            "baseName": "cartSubscriptionItems",
            "type": "Array<CartSubscriptionItem>"
        }    ];

    static getAttributeTypeMap() {
        return CreateCartSubscriptionItemsRequest.attributeTypeMap;
    }
}

