/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseCategory } from './baseCategory';

export class CreateCategoriesRequest {
    /**
    * Product Categories + products
    */
    'categories': Array<BaseCategory>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<BaseCategory>"
        }    ];

    static getAttributeTypeMap() {
        return CreateCategoriesRequest.attributeTypeMap;
    }
}

