/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionProductItemRequest } from './subscriptionProductItemRequest';

export class CreateSubscriptionProductCategoryRequest {
    /**
    * The name of the subscription product category.
    */
    'name': string;
    /**
    * The display order of the subscription product category.
    */
    'displayOrder'?: number;
    /**
    * Subscription products to be created within the category.
    */
    'subscriptionItems'?: Array<SubscriptionProductItemRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "displayOrder",
            "baseName": "displayOrder",
            "type": "number"
        },
        {
            "name": "subscriptionItems",
            "baseName": "subscriptionItems",
            "type": "Array<SubscriptionProductItemRequest>"
        }    ];

    static getAttributeTypeMap() {
        return CreateSubscriptionProductCategoryRequest.attributeTypeMap;
    }
}

