/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartFee } from './cartFee';

export class CreateCartFeesRequest {
    /**
    * A list of fees to be added to the cart.
    */
    'cartFees': Array<CartFee>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cartFees",
            "baseName": "cartFees",
            "type": "Array<CartFee>"
        }    ];

    static getAttributeTypeMap() {
        return CreateCartFeesRequest.attributeTypeMap;
    }
}

