/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartTaxRequestDto } from './cartTaxRequestDto';

export class CreateCartTaxesRequest {
    /**
    * Taxes.
    */
    'payload': Array<CartTaxRequestDto>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "payload",
            "baseName": "payload",
            "type": "Array<CartTaxRequestDto>"
        }    ];

    static getAttributeTypeMap() {
        return CreateCartTaxesRequest.attributeTypeMap;
    }
}

