/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseProductSite } from './baseProductSite';

export class CreateProductSitesRequest {
    /**
    * Product sites
    */
    'productSites': Array<BaseProductSite>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productSites",
            "baseName": "productSites",
            "type": "Array<BaseProductSite>"
        }    ];

    static getAttributeTypeMap() {
        return CreateProductSitesRequest.attributeTypeMap;
    }
}

