/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OmitGenericCreateSubscriptionProductSiteRequestDto } from './omitGenericCreateSubscriptionProductSiteRequestDto';

export class CreateSubscriptionProductSitesRequest {
    /**
    * Subscription Product sites
    */
    'subscriptionProductSites': Array<OmitGenericCreateSubscriptionProductSiteRequestDto>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscriptionProductSites",
            "baseName": "subscriptionProductSites",
            "type": "Array<OmitGenericCreateSubscriptionProductSiteRequestDto>"
        }    ];

    static getAttributeTypeMap() {
        return CreateSubscriptionProductSitesRequest.attributeTypeMap;
    }
}

