/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseCategory } from './baseCategory';

export class CreateSubscriptionProductCategoriesRequest {
    /**
    * Subscription Product Categories + products
    */
    'subscriptionProductCategories': Array<BaseCategory>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscriptionProductCategories",
            "baseName": "subscriptionProductCategories",
            "type": "Array<BaseCategory>"
        }    ];

    static getAttributeTypeMap() {
        return CreateSubscriptionProductCategoriesRequest.attributeTypeMap;
    }
}

