/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FeeResponse {
    /**
    * Fee UUID
    */
    'feeId': string;
    /**
    * Organization UUID
    */
    'orgId': string;
    /**
    * Site UUID
    */
    'siteId'?: string;
    /**
    * The name of the fee.
    */
    'name': string;
    /**
    * A description of the fee.
    */
    'description': string;
    /**
    * A fixed ammount fee to add.
    */
    'fixedAmount'?: number;
    /**
    * A percent fee to add.
    */
    'percentage'?: number;
    /**
    * Standard Fee Type ID
    */
    'standardFeeTypeId': string;
    /**
    * Codename of the standard fee type.
    */
    'standardFeeType': FeeResponse.StandardFeeTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "feeId",
            "baseName": "feeId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "fixedAmount",
            "baseName": "fixedAmount",
            "type": "number"
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "number"
        },
        {
            "name": "standardFeeTypeId",
            "baseName": "standardFeeTypeId",
            "type": "string"
        },
        {
            "name": "standardFeeType",
            "baseName": "standardFeeType",
            "type": "FeeResponse.StandardFeeTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return FeeResponse.attributeTypeMap;
    }
}

export namespace FeeResponse {
    export enum StandardFeeTypeEnum {
        FacilityFee = <any> 'facility_fee',
        LateFee = <any> 'late_fee',
        ConvenienceFee = <any> 'convenience_fee'
    }
}
