/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FeeTypeResponse {
    /**
    * Standard fee type UUID
    */
    'standardFeeTypeId': string;
    /**
    * The name of the fee.
    */
    'name': string;
    /**
    * Codename for the fee.
    */
    'codeName': FeeTypeResponse.CodeNameEnum;
    /**
    * A description of the fee.
    */
    'description': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "standardFeeTypeId",
            "baseName": "standardFeeTypeId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "codeName",
            "baseName": "codeName",
            "type": "FeeTypeResponse.CodeNameEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FeeTypeResponse.attributeTypeMap;
    }
}

export namespace FeeTypeResponse {
    export enum CodeNameEnum {
        FacilityFee = <any> 'facility_fee',
        LateFee = <any> 'late_fee',
        ConvenienceFee = <any> 'convenience_fee'
    }
}
