/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProductSiteResponse {
    /**
    * Id of the product
    */
    'productSiteId': string;
    /**
    * Price
    */
    'price': number;
    /**
    * Stock/Quantity
    */
    'stock': number;
    /**
    * Reorder level
    */
    'reorderLevel': number;
    /**
    * Currency code
    */
    'currency': string;
    /**
    * Product Category Id
    */
    'productCategoryId': string;
    /**
    * Identifier of product.
    */
    'productId': string;
    /**
    * Site Id
    */
    'siteId': string;
    /**
    * Organization Id
    */
    'orgId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productSiteId",
            "baseName": "productSiteId",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "stock",
            "baseName": "stock",
            "type": "number"
        },
        {
            "name": "reorderLevel",
            "baseName": "reorderLevel",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "productCategoryId",
            "baseName": "productCategoryId",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProductSiteResponse.attributeTypeMap;
    }
}

