/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProductResponse {
    /**
    * Id of the product
    */
    'productId': string;
    /**
    * Name of the product
    */
    'name': string;
    /**
    * Description of the product
    */
    'description': string;
    /**
    * Path to an image of the product
    */
    'imagePath': string | null;
    /**
    * Product Category Id
    */
    'productCategoryId': string;
    /**
    * Payment provider ID
    */
    'paymentProviderId': string;
    /**
    * Time of creation
    */
    'createdAt': Date;
    /**
    * userId of who created the product
    */
    'createdBy': string;
    /**
    * Time of the last update
    */
    'updatedAt': Date | null;
    /**
    * userId of who updated the product
    */
    'updatedBy': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "imagePath",
            "baseName": "imagePath",
            "type": "string"
        },
        {
            "name": "productCategoryId",
            "baseName": "productCategoryId",
            "type": "string"
        },
        {
            "name": "paymentProviderId",
            "baseName": "paymentProviderId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProductResponse.attributeTypeMap;
    }
}

