/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProductItemRequest {
    /**
    * Product Name
    */
    'name': string;
    /**
    * Product Description
    */
    'description': string;
    /**
    * Image path for the product
    */
    'imagePath'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "imagePath",
            "baseName": "imagePath",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProductItemRequest.attributeTypeMap;
    }
}

