/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionProductSiteResponse {
    /**
    * Id of the subscription product
    */
    'subscriptionProductSiteId': string;
    /**
    * Price
    */
    'price': number;
    /**
    * Currency code
    */
    'currency': string;
    /**
    * Product Category Id
    */
    'subscriptionProductCategoryId': string;
    /**
    * Identifier of subscription product.
    */
    'subscriptionProductId': string;
    /**
    * Site Id
    */
    'siteId': string;
    /**
    * Organization Id
    */
    'orgId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscriptionProductSiteId",
            "baseName": "subscriptionProductSiteId",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "subscriptionProductCategoryId",
            "baseName": "subscriptionProductCategoryId",
            "type": "string"
        },
        {
            "name": "subscriptionProductId",
            "baseName": "subscriptionProductId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionProductSiteResponse.attributeTypeMap;
    }
}

