/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionProductResponse } from './subscriptionProductResponse';

export class SubscriptionProductCategoryResponse {
    /**
    * The unique identifier for the subscription product category.
    */
    'subscriptionProductCategoryId': string;
    /**
    * The identifier of the organization that the subscription product category belongs to.
    */
    'orgId': string;
    /**
    * The name of the subscription product category.
    */
    'name': string;
    /**
    * The display order of the subscription product category.
    */
    'displayOrder': number;
    /**
    * The subscription products in this subscription product category.
    */
    'subscriptionItems': Array<SubscriptionProductResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscriptionProductCategoryId",
            "baseName": "subscriptionProductCategoryId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "displayOrder",
            "baseName": "displayOrder",
            "type": "number"
        },
        {
            "name": "subscriptionItems",
            "baseName": "subscriptionItems",
            "type": "Array<SubscriptionProductResponse>"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionProductCategoryResponse.attributeTypeMap;
    }
}

